name: Update list

on:
  schedule:
    - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: pip install -r requirements.txt
      - run: rm -rf data/
      - run: python fetch.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated update
          file_pattern: "*.json"
